global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'echo'
    scrape_interval: 30s
    static_configs:
      - targets:
        - 'host.docker.internal:8001'
        - 'host.docker.internal:8002'
